// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: roosha_service.proto
// Original file comments:
//
//  Copyright (c) 2016 Leo Khotov
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public License
//  version 3 along with this work.  If not, see <http://www.gnu.org/licenses/>.
//
#ifndef GRPC_roosha_5fservice_2eproto__INCLUDED
#define GRPC_roosha_5fservice_2eproto__INCLUDED

#include "roosha_service.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace roosha {
namespace translation {

class RooshaService GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status registrate(::grpc::ClientContext* context, const ::roosha::commons::Credentials& request, ::roosha::commons::AuthenticationToken* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::roosha::commons::AuthenticationToken>> Asyncregistrate(::grpc::ClientContext* context, const ::roosha::commons::Credentials& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::roosha::commons::AuthenticationToken>>(AsyncregistrateRaw(context, request, cq));
    }
    virtual ::grpc::Status authorize(::grpc::ClientContext* context, const ::roosha::commons::Credentials& request, ::roosha::commons::AuthenticationToken* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::roosha::commons::AuthenticationToken>> Asyncauthorize(::grpc::ClientContext* context, const ::roosha::commons::Credentials& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::roosha::commons::AuthenticationToken>>(AsyncauthorizeRaw(context, request, cq));
    }
    virtual ::grpc::Status translate(::grpc::ClientContext* context, const ::roosha::translation::TranslationRequest& request, ::roosha::translation::Translations* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::roosha::translation::Translations>> Asynctranslate(::grpc::ClientContext* context, const ::roosha::translation::TranslationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::roosha::translation::Translations>>(AsynctranslateRaw(context, request, cq));
    }
    virtual ::grpc::Status proposeUserTranslations(::grpc::ClientContext* context, const ::roosha::translation::UserTranslationsProposal& request, ::roosha::commons::Void* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::roosha::commons::Void>> AsyncproposeUserTranslations(::grpc::ClientContext* context, const ::roosha::translation::UserTranslationsProposal& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::roosha::commons::Void>>(AsyncproposeUserTranslationsRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::roosha::commons::AuthenticationToken>* AsyncregistrateRaw(::grpc::ClientContext* context, const ::roosha::commons::Credentials& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::roosha::commons::AuthenticationToken>* AsyncauthorizeRaw(::grpc::ClientContext* context, const ::roosha::commons::Credentials& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::roosha::translation::Translations>* AsynctranslateRaw(::grpc::ClientContext* context, const ::roosha::translation::TranslationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::roosha::commons::Void>* AsyncproposeUserTranslationsRaw(::grpc::ClientContext* context, const ::roosha::translation::UserTranslationsProposal& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status registrate(::grpc::ClientContext* context, const ::roosha::commons::Credentials& request, ::roosha::commons::AuthenticationToken* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::roosha::commons::AuthenticationToken>> Asyncregistrate(::grpc::ClientContext* context, const ::roosha::commons::Credentials& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::roosha::commons::AuthenticationToken>>(AsyncregistrateRaw(context, request, cq));
    }
    ::grpc::Status authorize(::grpc::ClientContext* context, const ::roosha::commons::Credentials& request, ::roosha::commons::AuthenticationToken* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::roosha::commons::AuthenticationToken>> Asyncauthorize(::grpc::ClientContext* context, const ::roosha::commons::Credentials& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::roosha::commons::AuthenticationToken>>(AsyncauthorizeRaw(context, request, cq));
    }
    ::grpc::Status translate(::grpc::ClientContext* context, const ::roosha::translation::TranslationRequest& request, ::roosha::translation::Translations* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::roosha::translation::Translations>> Asynctranslate(::grpc::ClientContext* context, const ::roosha::translation::TranslationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::roosha::translation::Translations>>(AsynctranslateRaw(context, request, cq));
    }
    ::grpc::Status proposeUserTranslations(::grpc::ClientContext* context, const ::roosha::translation::UserTranslationsProposal& request, ::roosha::commons::Void* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::roosha::commons::Void>> AsyncproposeUserTranslations(::grpc::ClientContext* context, const ::roosha::translation::UserTranslationsProposal& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::roosha::commons::Void>>(AsyncproposeUserTranslationsRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::roosha::commons::AuthenticationToken>* AsyncregistrateRaw(::grpc::ClientContext* context, const ::roosha::commons::Credentials& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::roosha::commons::AuthenticationToken>* AsyncauthorizeRaw(::grpc::ClientContext* context, const ::roosha::commons::Credentials& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::roosha::translation::Translations>* AsynctranslateRaw(::grpc::ClientContext* context, const ::roosha::translation::TranslationRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::roosha::commons::Void>* AsyncproposeUserTranslationsRaw(::grpc::ClientContext* context, const ::roosha::translation::UserTranslationsProposal& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_registrate_;
    const ::grpc::RpcMethod rpcmethod_authorize_;
    const ::grpc::RpcMethod rpcmethod_translate_;
    const ::grpc::RpcMethod rpcmethod_proposeUserTranslations_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status registrate(::grpc::ServerContext* context, const ::roosha::commons::Credentials* request, ::roosha::commons::AuthenticationToken* response);
    virtual ::grpc::Status authorize(::grpc::ServerContext* context, const ::roosha::commons::Credentials* request, ::roosha::commons::AuthenticationToken* response);
    virtual ::grpc::Status translate(::grpc::ServerContext* context, const ::roosha::translation::TranslationRequest* request, ::roosha::translation::Translations* response);
    virtual ::grpc::Status proposeUserTranslations(::grpc::ServerContext* context, const ::roosha::translation::UserTranslationsProposal* request, ::roosha::commons::Void* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_registrate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_registrate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_registrate() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registrate(::grpc::ServerContext* context, const ::roosha::commons::Credentials* request, ::roosha::commons::AuthenticationToken* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestregistrate(::grpc::ServerContext* context, ::roosha::commons::Credentials* request, ::grpc::ServerAsyncResponseWriter< ::roosha::commons::AuthenticationToken>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_authorize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_authorize() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_authorize() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status authorize(::grpc::ServerContext* context, const ::roosha::commons::Credentials* request, ::roosha::commons::AuthenticationToken* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestauthorize(::grpc::ServerContext* context, ::roosha::commons::Credentials* request, ::grpc::ServerAsyncResponseWriter< ::roosha::commons::AuthenticationToken>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_translate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_translate() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_translate() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status translate(::grpc::ServerContext* context, const ::roosha::translation::TranslationRequest* request, ::roosha::translation::Translations* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requesttranslate(::grpc::ServerContext* context, ::roosha::translation::TranslationRequest* request, ::grpc::ServerAsyncResponseWriter< ::roosha::translation::Translations>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_proposeUserTranslations : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_proposeUserTranslations() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_proposeUserTranslations() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status proposeUserTranslations(::grpc::ServerContext* context, const ::roosha::translation::UserTranslationsProposal* request, ::roosha::commons::Void* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestproposeUserTranslations(::grpc::ServerContext* context, ::roosha::translation::UserTranslationsProposal* request, ::grpc::ServerAsyncResponseWriter< ::roosha::commons::Void>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_registrate<WithAsyncMethod_authorize<WithAsyncMethod_translate<WithAsyncMethod_proposeUserTranslations<Service > > > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_registrate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_registrate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_registrate() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registrate(::grpc::ServerContext* context, const ::roosha::commons::Credentials* request, ::roosha::commons::AuthenticationToken* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_authorize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_authorize() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_authorize() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status authorize(::grpc::ServerContext* context, const ::roosha::commons::Credentials* request, ::roosha::commons::AuthenticationToken* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_translate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_translate() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_translate() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status translate(::grpc::ServerContext* context, const ::roosha::translation::TranslationRequest* request, ::roosha::translation::Translations* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_proposeUserTranslations : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_proposeUserTranslations() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_proposeUserTranslations() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status proposeUserTranslations(::grpc::ServerContext* context, const ::roosha::translation::UserTranslationsProposal* request, ::roosha::commons::Void* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace translation
}  // namespace roosha


#endif  // GRPC_roosha_5fservice_2eproto__INCLUDED
