// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roosha_service.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "roosha_service.pb.h"

#include <algorithm>

#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace roosha {
<<<<<<< HEAD
=======
class PullRequestDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<PullRequest> {
} _PullRequest_default_instance_;
>>>>>>> synchronization
class TranslationRequestDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<TranslationRequest> {
} _TranslationRequest_default_instance_;
class TranslationsDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Translations> {
} _Translations_default_instance_;
class TranslationDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Translation> {
} _Translation_default_instance_;

namespace protobuf_roosha_5fservice_2eproto {


namespace {

<<<<<<< HEAD
::google::protobuf::Metadata file_level_metadata[3];
=======
::google::protobuf::Metadata file_level_metadata[4];
>>>>>>> synchronization
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
<<<<<<< HEAD
=======
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PullRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PullRequest, synchronized_prefix_length_),
  ~0u,  // no _has_bits_
>>>>>>> synchronization
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TranslationRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TranslationRequest, source_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Translations, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Translations, source_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Translations, translation_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Translation, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Translation, target_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Translation, example_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Translation, provider_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
<<<<<<< HEAD
  { 0, -1, sizeof(TranslationRequest)},
  { 5, -1, sizeof(Translations)},
  { 11, -1, sizeof(Translation)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
=======
  { 0, -1, sizeof(PullRequest)},
  { 5, -1, sizeof(TranslationRequest)},
  { 10, -1, sizeof(Translations)},
  { 16, -1, sizeof(Translation)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_PullRequest_default_instance_),
>>>>>>> synchronization
  reinterpret_cast<const ::google::protobuf::Message*>(&_TranslationRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Translations_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Translation_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "roosha_service.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
<<<<<<< HEAD
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
=======
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
>>>>>>> synchronization
}

}  // namespace

void TableStruct::Shutdown() {
<<<<<<< HEAD
  _TranslationRequest_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _Translations_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _Translation_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
=======
  _PullRequest_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _TranslationRequest_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _Translations_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _Translation_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
>>>>>>> synchronization
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::roosha::protobuf_commons_2eproto::InitDefaults();
  ::roosha::protobuf_changes_2eproto::InitDefaults();
<<<<<<< HEAD
=======
  _PullRequest_default_instance_.DefaultConstruct();
>>>>>>> synchronization
  _TranslationRequest_default_instance_.DefaultConstruct();
  _Translations_default_instance_.DefaultConstruct();
  _Translation_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\024roosha_service.proto\022\006roosha\032\rcommons."
<<<<<<< HEAD
      "proto\032\rchanges.proto\"$\n\022TranslationReque"
      "st\022\016\n\006source\030\001 \001(\t\"H\n\014Translations\022\016\n\006so"
      "urce\030\001 \001(\t\022(\n\013translation\030\002 \003(\0132\023.roosha"
      ".Translation\"]\n\013Translation\022\016\n\006target\030\001 "
      "\003(\t\022\017\n\007example\030\002 \003(\t\022-\n\010provider\030\003 \001(\0162\033"
      ".roosha.TranslationProvider*P\n\023Translati"
      "onProvider\022\013\n\007UNKNOWN\020\000\022\025\n\021YANDEX_DICTIO"
      "NARY\020\001\022\025\n\021YANDEX_TRANSLATOR\020\0022\217\003\n\rRoosha"
      "Service\022#\n\005knock\022\014.roosha.Void\032\014.roosha."
      "Void\022>\n\nregistrate\022\023.roosha.Credentials\032"
      "\033.roosha.AuthenticationToken\022=\n\tauthoriz"
      "e\022\023.roosha.Credentials\032\033.roosha.Authenti"
      "cationToken\022=\n\ttranslate\022\032.roosha.Transl"
      "ationRequest\032\024.roosha.Translations\022=\n\027pr"
      "oposeUserTranslations\022\024.roosha.Translati"
      "ons\032\014.roosha.Void\022-\n\013saveChanges\022\016.roosh"
      "a.Change\032\014.roosha.Void(\001\022-\n\013loadChanges\022"
      "\014.roosha.Void\032\016.roosha.Change0\001B7\n\027com.g"
      "ithub.roosha.protoB\027TranslationServicePr"
      "otoH\001\370\001\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 816);
=======
      "proto\032\rchanges.proto\"1\n\013PullRequest\022\"\n\032s"
      "ynchronized_prefix_length\030\001 \001(\005\"$\n\022Trans"
      "lationRequest\022\016\n\006source\030\001 \001(\t\"H\n\014Transla"
      "tions\022\016\n\006source\030\001 \001(\t\022(\n\013translation\030\002 \003"
      "(\0132\023.roosha.Translation\"]\n\013Translation\022\016"
      "\n\006target\030\001 \003(\t\022\017\n\007example\030\002 \003(\t\022-\n\010provi"
      "der\030\003 \001(\0162\033.roosha.TranslationProvider*P"
      "\n\023TranslationProvider\022\013\n\007UNKNOWN\020\000\022\025\n\021YA"
      "NDEX_DICTIONARY\020\001\022\025\n\021YANDEX_TRANSLATOR\020\002"
      "2\226\003\n\rRooshaService\022#\n\005knock\022\014.roosha.Voi"
      "d\032\014.roosha.Void\022>\n\nregistrate\022\023.roosha.C"
      "redentials\032\033.roosha.AuthenticationToken\022"
      "=\n\tauthorize\022\023.roosha.Credentials\032\033.roos"
      "ha.AuthenticationToken\022=\n\ttranslate\022\032.ro"
      "osha.TranslationRequest\032\024.roosha.Transla"
      "tions\022=\n\027proposeUserTranslations\022\024.roosh"
      "a.Translations\032\014.roosha.Void\022-\n\013saveChan"
      "ges\022\016.roosha.Change\032\014.roosha.Void(\001\0224\n\013l"
      "oadChanges\022\023.roosha.PullRequest\032\016.roosha"
      ".Change0\001B7\n\027com.github.roosha.protoB\027Tr"
      "anslationServiceProtoH\001\370\001\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 874);
>>>>>>> synchronization
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "roosha_service.proto", &protobuf_RegisterTypes);
  ::roosha::protobuf_commons_2eproto::AddDescriptors();
  ::roosha::protobuf_changes_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_roosha_5fservice_2eproto

const ::google::protobuf::EnumDescriptor* TranslationProvider_descriptor() {
  protobuf_roosha_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_roosha_5fservice_2eproto::file_level_enum_descriptors[0];
}
bool TranslationProvider_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PullRequest::kSynchronizedPrefixLengthFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PullRequest::PullRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_roosha_5fservice_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:roosha.PullRequest)
}
PullRequest::PullRequest(const PullRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  synchronized_prefix_length_ = from.synchronized_prefix_length_;
  // @@protoc_insertion_point(copy_constructor:roosha.PullRequest)
}

void PullRequest::SharedCtor() {
  synchronized_prefix_length_ = 0;
  _cached_size_ = 0;
}

PullRequest::~PullRequest() {
  // @@protoc_insertion_point(destructor:roosha.PullRequest)
  SharedDtor();
}

void PullRequest::SharedDtor() {
}

void PullRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PullRequest::descriptor() {
  protobuf_roosha_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_roosha_5fservice_2eproto::file_level_metadata[0].descriptor;
}

const PullRequest& PullRequest::default_instance() {
  protobuf_roosha_5fservice_2eproto::InitDefaults();
  return *internal_default_instance();
}

PullRequest* PullRequest::New(::google::protobuf::Arena* arena) const {
  PullRequest* n = new PullRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PullRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:roosha.PullRequest)
  synchronized_prefix_length_ = 0;
}

bool PullRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:roosha.PullRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 synchronized_prefix_length = 1;
      case 1: {
        if (tag == 8u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &synchronized_prefix_length_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:roosha.PullRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:roosha.PullRequest)
  return false;
#undef DO_
}

void PullRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:roosha.PullRequest)
  // int32 synchronized_prefix_length = 1;
  if (this->synchronized_prefix_length() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->synchronized_prefix_length(), output);
  }

  // @@protoc_insertion_point(serialize_end:roosha.PullRequest)
}

::google::protobuf::uint8* PullRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:roosha.PullRequest)
  // int32 synchronized_prefix_length = 1;
  if (this->synchronized_prefix_length() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->synchronized_prefix_length(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:roosha.PullRequest)
  return target;
}

size_t PullRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:roosha.PullRequest)
  size_t total_size = 0;

  // int32 synchronized_prefix_length = 1;
  if (this->synchronized_prefix_length() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->synchronized_prefix_length());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PullRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:roosha.PullRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const PullRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PullRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:roosha.PullRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:roosha.PullRequest)
    MergeFrom(*source);
  }
}

void PullRequest::MergeFrom(const PullRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:roosha.PullRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.synchronized_prefix_length() != 0) {
    set_synchronized_prefix_length(from.synchronized_prefix_length());
  }
}

void PullRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:roosha.PullRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PullRequest::CopyFrom(const PullRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:roosha.PullRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}
<<<<<<< HEAD
=======

bool PullRequest::IsInitialized() const {
  return true;
}

void PullRequest::Swap(PullRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PullRequest::InternalSwap(PullRequest* other) {
  std::swap(synchronized_prefix_length_, other->synchronized_prefix_length_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PullRequest::GetMetadata() const {
  protobuf_roosha_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_roosha_5fservice_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PullRequest

// int32 synchronized_prefix_length = 1;
void PullRequest::clear_synchronized_prefix_length() {
  synchronized_prefix_length_ = 0;
}
::google::protobuf::int32 PullRequest::synchronized_prefix_length() const {
  // @@protoc_insertion_point(field_get:roosha.PullRequest.synchronized_prefix_length)
  return synchronized_prefix_length_;
}
void PullRequest::set_synchronized_prefix_length(::google::protobuf::int32 value) {
  
  synchronized_prefix_length_ = value;
  // @@protoc_insertion_point(field_set:roosha.PullRequest.synchronized_prefix_length)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TranslationRequest::kSourceFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TranslationRequest::TranslationRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_roosha_5fservice_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:roosha.TranslationRequest)
}
>>>>>>> synchronization
TranslationRequest::TranslationRequest(const TranslationRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  source_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.source().size() > 0) {
    source_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.source_);
  }
  // @@protoc_insertion_point(copy_constructor:roosha.TranslationRequest)
}

void TranslationRequest::SharedCtor() {
  source_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

TranslationRequest::~TranslationRequest() {
  // @@protoc_insertion_point(destructor:roosha.TranslationRequest)
  SharedDtor();
}

void TranslationRequest::SharedDtor() {
  source_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void TranslationRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TranslationRequest::descriptor() {
  protobuf_roosha_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
<<<<<<< HEAD
  return protobuf_roosha_5fservice_2eproto::file_level_metadata[0].descriptor;
=======
  return protobuf_roosha_5fservice_2eproto::file_level_metadata[1].descriptor;
>>>>>>> synchronization
}

const TranslationRequest& TranslationRequest::default_instance() {
  protobuf_roosha_5fservice_2eproto::InitDefaults();
  return *internal_default_instance();
}

TranslationRequest* TranslationRequest::New(::google::protobuf::Arena* arena) const {
  TranslationRequest* n = new TranslationRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TranslationRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:roosha.TranslationRequest)
  source_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool TranslationRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:roosha.TranslationRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string source = 1;
      case 1: {
        if (tag == 10u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_source()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->source().data(), this->source().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "roosha.TranslationRequest.source"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:roosha.TranslationRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:roosha.TranslationRequest)
  return false;
#undef DO_
}

void TranslationRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:roosha.TranslationRequest)
  // string source = 1;
  if (this->source().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->source().data(), this->source().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "roosha.TranslationRequest.source");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->source(), output);
  }

  // @@protoc_insertion_point(serialize_end:roosha.TranslationRequest)
}

::google::protobuf::uint8* TranslationRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:roosha.TranslationRequest)
  // string source = 1;
  if (this->source().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->source().data(), this->source().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "roosha.TranslationRequest.source");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->source(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:roosha.TranslationRequest)
  return target;
}

size_t TranslationRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:roosha.TranslationRequest)
  size_t total_size = 0;

  // string source = 1;
  if (this->source().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->source());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TranslationRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:roosha.TranslationRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const TranslationRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TranslationRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:roosha.TranslationRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:roosha.TranslationRequest)
    MergeFrom(*source);
  }
}

void TranslationRequest::MergeFrom(const TranslationRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:roosha.TranslationRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.source().size() > 0) {

    source_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.source_);
  }
}

void TranslationRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:roosha.TranslationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TranslationRequest::CopyFrom(const TranslationRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:roosha.TranslationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TranslationRequest::IsInitialized() const {
  return true;
}

void TranslationRequest::Swap(TranslationRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TranslationRequest::InternalSwap(TranslationRequest* other) {
  source_.Swap(&other->source_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TranslationRequest::GetMetadata() const {
  protobuf_roosha_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
<<<<<<< HEAD
  return protobuf_roosha_5fservice_2eproto::file_level_metadata[0];
=======
  return protobuf_roosha_5fservice_2eproto::file_level_metadata[1];
>>>>>>> synchronization
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TranslationRequest

// string source = 1;
void TranslationRequest::clear_source() {
  source_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& TranslationRequest::source() const {
  // @@protoc_insertion_point(field_get:roosha.TranslationRequest.source)
  return source_.GetNoArena();
}
void TranslationRequest::set_source(const ::std::string& value) {
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:roosha.TranslationRequest.source)
}
#if LANG_CXX11
void TranslationRequest::set_source(::std::string&& value) {
  
  source_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:roosha.TranslationRequest.source)
}
#endif
void TranslationRequest::set_source(const char* value) {
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:roosha.TranslationRequest.source)
}
void TranslationRequest::set_source(const char* value, size_t size) {
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:roosha.TranslationRequest.source)
}
::std::string* TranslationRequest::mutable_source() {
  
  // @@protoc_insertion_point(field_mutable:roosha.TranslationRequest.source)
  return source_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* TranslationRequest::release_source() {
  // @@protoc_insertion_point(field_release:roosha.TranslationRequest.source)
  
  return source_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TranslationRequest::set_allocated_source(::std::string* source) {
  if (source != NULL) {
    
  } else {
    
  }
  source_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), source);
  // @@protoc_insertion_point(field_set_allocated:roosha.TranslationRequest.source)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Translations::kSourceFieldNumber;
const int Translations::kTranslationFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Translations::Translations()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_roosha_5fservice_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:roosha.Translations)
}
Translations::Translations(const Translations& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      translation_(from.translation_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  source_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.source().size() > 0) {
    source_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.source_);
  }
  // @@protoc_insertion_point(copy_constructor:roosha.Translations)
}

void Translations::SharedCtor() {
  source_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

Translations::~Translations() {
  // @@protoc_insertion_point(destructor:roosha.Translations)
  SharedDtor();
}

void Translations::SharedDtor() {
  source_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Translations::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Translations::descriptor() {
  protobuf_roosha_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
<<<<<<< HEAD
  return protobuf_roosha_5fservice_2eproto::file_level_metadata[1].descriptor;
=======
  return protobuf_roosha_5fservice_2eproto::file_level_metadata[2].descriptor;
>>>>>>> synchronization
}

const Translations& Translations::default_instance() {
  protobuf_roosha_5fservice_2eproto::InitDefaults();
  return *internal_default_instance();
}

Translations* Translations::New(::google::protobuf::Arena* arena) const {
  Translations* n = new Translations;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Translations::Clear() {
// @@protoc_insertion_point(message_clear_start:roosha.Translations)
  translation_.Clear();
  source_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Translations::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:roosha.Translations)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string source = 1;
      case 1: {
        if (tag == 10u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_source()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->source().data(), this->source().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "roosha.Translations.source"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .roosha.Translation translation = 2;
      case 2: {
        if (tag == 18u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_translation()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:roosha.Translations)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:roosha.Translations)
  return false;
#undef DO_
}

void Translations::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:roosha.Translations)
  // string source = 1;
  if (this->source().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->source().data(), this->source().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "roosha.Translations.source");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->source(), output);
  }

  // repeated .roosha.Translation translation = 2;
  for (unsigned int i = 0, n = this->translation_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->translation(i), output);
  }

  // @@protoc_insertion_point(serialize_end:roosha.Translations)
}

::google::protobuf::uint8* Translations::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:roosha.Translations)
  // string source = 1;
  if (this->source().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->source().data(), this->source().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "roosha.Translations.source");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->source(), target);
  }

  // repeated .roosha.Translation translation = 2;
  for (unsigned int i = 0, n = this->translation_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->translation(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:roosha.Translations)
  return target;
}

size_t Translations::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:roosha.Translations)
  size_t total_size = 0;
<<<<<<< HEAD

  // repeated .roosha.Translation translation = 2;
  {
    unsigned int count = this->translation_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->translation(i));
    }
  }

=======

  // repeated .roosha.Translation translation = 2;
  {
    unsigned int count = this->translation_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->translation(i));
    }
  }

>>>>>>> synchronization
  // string source = 1;
  if (this->source().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->source());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Translations::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:roosha.Translations)
  GOOGLE_DCHECK_NE(&from, this);
  const Translations* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Translations>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:roosha.Translations)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:roosha.Translations)
    MergeFrom(*source);
  }
}

void Translations::MergeFrom(const Translations& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:roosha.Translations)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  translation_.MergeFrom(from.translation_);
  if (from.source().size() > 0) {

    source_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.source_);
  }
}

void Translations::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:roosha.Translations)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Translations::CopyFrom(const Translations& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:roosha.Translations)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Translations::IsInitialized() const {
  return true;
}

void Translations::Swap(Translations* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Translations::InternalSwap(Translations* other) {
  translation_.UnsafeArenaSwap(&other->translation_);
  source_.Swap(&other->source_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Translations::GetMetadata() const {
  protobuf_roosha_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
<<<<<<< HEAD
  return protobuf_roosha_5fservice_2eproto::file_level_metadata[1];
=======
  return protobuf_roosha_5fservice_2eproto::file_level_metadata[2];
>>>>>>> synchronization
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Translations

// string source = 1;
void Translations::clear_source() {
  source_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Translations::source() const {
  // @@protoc_insertion_point(field_get:roosha.Translations.source)
  return source_.GetNoArena();
}
void Translations::set_source(const ::std::string& value) {
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:roosha.Translations.source)
}
#if LANG_CXX11
void Translations::set_source(::std::string&& value) {
  
  source_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:roosha.Translations.source)
}
#endif
void Translations::set_source(const char* value) {
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:roosha.Translations.source)
}
void Translations::set_source(const char* value, size_t size) {
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:roosha.Translations.source)
}
::std::string* Translations::mutable_source() {
  
  // @@protoc_insertion_point(field_mutable:roosha.Translations.source)
  return source_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Translations::release_source() {
  // @@protoc_insertion_point(field_release:roosha.Translations.source)
  
  return source_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Translations::set_allocated_source(::std::string* source) {
  if (source != NULL) {
    
  } else {
    
  }
  source_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), source);
  // @@protoc_insertion_point(field_set_allocated:roosha.Translations.source)
}

// repeated .roosha.Translation translation = 2;
int Translations::translation_size() const {
  return translation_.size();
}
void Translations::clear_translation() {
  translation_.Clear();
}
const ::roosha::Translation& Translations::translation(int index) const {
  // @@protoc_insertion_point(field_get:roosha.Translations.translation)
  return translation_.Get(index);
}
::roosha::Translation* Translations::mutable_translation(int index) {
  // @@protoc_insertion_point(field_mutable:roosha.Translations.translation)
  return translation_.Mutable(index);
}
::roosha::Translation* Translations::add_translation() {
  // @@protoc_insertion_point(field_add:roosha.Translations.translation)
  return translation_.Add();
}
::google::protobuf::RepeatedPtrField< ::roosha::Translation >*
Translations::mutable_translation() {
  // @@protoc_insertion_point(field_mutable_list:roosha.Translations.translation)
  return &translation_;
}
const ::google::protobuf::RepeatedPtrField< ::roosha::Translation >&
Translations::translation() const {
  // @@protoc_insertion_point(field_list:roosha.Translations.translation)
  return translation_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Translation::kTargetFieldNumber;
const int Translation::kExampleFieldNumber;
const int Translation::kProviderFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Translation::Translation()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_roosha_5fservice_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:roosha.Translation)
}
Translation::Translation(const Translation& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      target_(from.target_),
      example_(from.example_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  provider_ = from.provider_;
  // @@protoc_insertion_point(copy_constructor:roosha.Translation)
}

void Translation::SharedCtor() {
  provider_ = 0;
  _cached_size_ = 0;
}

Translation::~Translation() {
  // @@protoc_insertion_point(destructor:roosha.Translation)
  SharedDtor();
}

void Translation::SharedDtor() {
}

void Translation::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Translation::descriptor() {
  protobuf_roosha_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
<<<<<<< HEAD
  return protobuf_roosha_5fservice_2eproto::file_level_metadata[2].descriptor;
=======
  return protobuf_roosha_5fservice_2eproto::file_level_metadata[3].descriptor;
>>>>>>> synchronization
}

const Translation& Translation::default_instance() {
  protobuf_roosha_5fservice_2eproto::InitDefaults();
  return *internal_default_instance();
}

Translation* Translation::New(::google::protobuf::Arena* arena) const {
  Translation* n = new Translation;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Translation::Clear() {
// @@protoc_insertion_point(message_clear_start:roosha.Translation)
  target_.Clear();
  example_.Clear();
  provider_ = 0;
}

bool Translation::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:roosha.Translation)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string target = 1;
      case 1: {
        if (tag == 10u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_target()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->target(this->target_size() - 1).data(),
            this->target(this->target_size() - 1).length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "roosha.Translation.target"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string example = 2;
      case 2: {
        if (tag == 18u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_example()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->example(this->example_size() - 1).data(),
            this->example(this->example_size() - 1).length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "roosha.Translation.example"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .roosha.TranslationProvider provider = 3;
      case 3: {
        if (tag == 24u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_provider(static_cast< ::roosha::TranslationProvider >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:roosha.Translation)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:roosha.Translation)
  return false;
#undef DO_
}

void Translation::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:roosha.Translation)
  // repeated string target = 1;
  for (int i = 0; i < this->target_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->target(i).data(), this->target(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "roosha.Translation.target");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->target(i), output);
  }

  // repeated string example = 2;
  for (int i = 0; i < this->example_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->example(i).data(), this->example(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "roosha.Translation.example");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->example(i), output);
  }

  // .roosha.TranslationProvider provider = 3;
  if (this->provider() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->provider(), output);
  }

  // @@protoc_insertion_point(serialize_end:roosha.Translation)
}

::google::protobuf::uint8* Translation::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:roosha.Translation)
  // repeated string target = 1;
  for (int i = 0; i < this->target_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->target(i).data(), this->target(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "roosha.Translation.target");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->target(i), target);
  }

  // repeated string example = 2;
  for (int i = 0; i < this->example_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->example(i).data(), this->example(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "roosha.Translation.example");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->example(i), target);
  }

  // .roosha.TranslationProvider provider = 3;
  if (this->provider() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->provider(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:roosha.Translation)
  return target;
}

size_t Translation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:roosha.Translation)
  size_t total_size = 0;

  // repeated string target = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->target_size());
  for (int i = 0; i < this->target_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->target(i));
  }

  // repeated string example = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->example_size());
  for (int i = 0; i < this->example_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->example(i));
  }

  // .roosha.TranslationProvider provider = 3;
  if (this->provider() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->provider());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Translation::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:roosha.Translation)
  GOOGLE_DCHECK_NE(&from, this);
  const Translation* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Translation>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:roosha.Translation)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:roosha.Translation)
    MergeFrom(*source);
  }
}

void Translation::MergeFrom(const Translation& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:roosha.Translation)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  target_.MergeFrom(from.target_);
  example_.MergeFrom(from.example_);
  if (from.provider() != 0) {
    set_provider(from.provider());
  }
}

void Translation::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:roosha.Translation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Translation::CopyFrom(const Translation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:roosha.Translation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Translation::IsInitialized() const {
  return true;
}

void Translation::Swap(Translation* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Translation::InternalSwap(Translation* other) {
  target_.UnsafeArenaSwap(&other->target_);
  example_.UnsafeArenaSwap(&other->example_);
  std::swap(provider_, other->provider_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Translation::GetMetadata() const {
  protobuf_roosha_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
<<<<<<< HEAD
  return protobuf_roosha_5fservice_2eproto::file_level_metadata[2];
=======
  return protobuf_roosha_5fservice_2eproto::file_level_metadata[3];
>>>>>>> synchronization
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Translation

// repeated string target = 1;
int Translation::target_size() const {
  return target_.size();
}
void Translation::clear_target() {
  target_.Clear();
}
const ::std::string& Translation::target(int index) const {
  // @@protoc_insertion_point(field_get:roosha.Translation.target)
  return target_.Get(index);
}
::std::string* Translation::mutable_target(int index) {
  // @@protoc_insertion_point(field_mutable:roosha.Translation.target)
  return target_.Mutable(index);
}
void Translation::set_target(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:roosha.Translation.target)
  target_.Mutable(index)->assign(value);
}
void Translation::set_target(int index, const char* value) {
  target_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:roosha.Translation.target)
}
void Translation::set_target(int index, const char* value, size_t size) {
  target_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:roosha.Translation.target)
}
::std::string* Translation::add_target() {
  // @@protoc_insertion_point(field_add_mutable:roosha.Translation.target)
  return target_.Add();
}
void Translation::add_target(const ::std::string& value) {
  target_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:roosha.Translation.target)
}
void Translation::add_target(const char* value) {
  target_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:roosha.Translation.target)
}
void Translation::add_target(const char* value, size_t size) {
  target_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:roosha.Translation.target)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
Translation::target() const {
  // @@protoc_insertion_point(field_list:roosha.Translation.target)
  return target_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
Translation::mutable_target() {
  // @@protoc_insertion_point(field_mutable_list:roosha.Translation.target)
  return &target_;
}

// repeated string example = 2;
int Translation::example_size() const {
  return example_.size();
}
void Translation::clear_example() {
  example_.Clear();
}
const ::std::string& Translation::example(int index) const {
  // @@protoc_insertion_point(field_get:roosha.Translation.example)
  return example_.Get(index);
}
::std::string* Translation::mutable_example(int index) {
  // @@protoc_insertion_point(field_mutable:roosha.Translation.example)
  return example_.Mutable(index);
}
void Translation::set_example(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:roosha.Translation.example)
  example_.Mutable(index)->assign(value);
}
void Translation::set_example(int index, const char* value) {
  example_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:roosha.Translation.example)
}
void Translation::set_example(int index, const char* value, size_t size) {
  example_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:roosha.Translation.example)
}
::std::string* Translation::add_example() {
  // @@protoc_insertion_point(field_add_mutable:roosha.Translation.example)
  return example_.Add();
}
void Translation::add_example(const ::std::string& value) {
  example_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:roosha.Translation.example)
}
void Translation::add_example(const char* value) {
  example_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:roosha.Translation.example)
}
void Translation::add_example(const char* value, size_t size) {
  example_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:roosha.Translation.example)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
Translation::example() const {
  // @@protoc_insertion_point(field_list:roosha.Translation.example)
  return example_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
Translation::mutable_example() {
  // @@protoc_insertion_point(field_mutable_list:roosha.Translation.example)
  return &example_;
}

// .roosha.TranslationProvider provider = 3;
void Translation::clear_provider() {
  provider_ = 0;
}
::roosha::TranslationProvider Translation::provider() const {
  // @@protoc_insertion_point(field_get:roosha.Translation.provider)
  return static_cast< ::roosha::TranslationProvider >(provider_);
}
void Translation::set_provider(::roosha::TranslationProvider value) {
  
  provider_ = value;
  // @@protoc_insertion_point(field_set:roosha.Translation.provider)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace roosha

// @@protoc_insertion_point(global_scope)
